export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_FAIL = 'AUTH_FAIL';

export const FETCH_MOBILES = 'FETCH_MOBILES';
export const CREATE_MOBILE = 'CREATE_MOBILE';
export const EDIT_MOBILE = 'EDIT_MOBILE';
export const DELETE_MOBILE = 'DELETE_MOBILE';
export const MOBILE_ERROR = 'MOBILE_ERROR';
export const MOBILES_LOADING = 'MOBILES_LOADING';

export const FETCH_CARTS = 'FETCH_CARTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_CART_QUANTITY_BY_ONE = 'INCREASE_CART_QUANTITY_BY_ONE';
export const DECREASE_CART_QUANTITY_BY_ONE = 'DECREASE_CART_QUANTITY_BY_ONE';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';